import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import Header from "@/components/Header";
import FooterGlow from "@/components/mvpblocks/footer-glow";
import CTA1 from "@/components/mvpblocks/cta-1";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-black  antialiased`}
      >
        <Header />

        {children}
        <CTA1/>
        <FooterGlow />
      </body>
    </html>
  );
}
